#  Anand International College of Engineering Subject
# Data Science with AI&MLops  
## Date : 23/06/2026 
## Topic – Pandas    
## Assignment 5:

 1. Explain pandas and its role in Data Analysis and Machine Learning.

Pandas is an open-source Python library used for data manipulation, analysis, and cleaning.

Main Data Structures in Pandas
1. Series

A Series is a one-dimensional labeled array.

In [57]:
import pandas as pd 
import numpy as np

a = pd.Series([5,10,15,20,25,30])
print(a)

0     5
1    10
2    15
3    20
4    25
5    30
dtype: int64

2. DataFrame

A DataFrame is a two-dimensional table with rows and columns.

In [58]:
data = {
    "Name": ["Ankush", "Rahul", "Aman"],
    "Age": [20, 21, 22]
}

df = pd.DataFrame(data)
print(df)

     Name  Age
0  Ankush   20
1   Rahul   21
2    Aman   22

## Role of Pandas in Data Analysis

### Pandas helps analysts perform various operations on data efficiently.

1. Reading data  eg:- CSV
2. Data inspection
df.head()      # First 5 rows
df.tail()      # Last 5 rows
df.info()      # Dataset information
df.describe()  # Statistical summary
3. Data Cleaning
Handling missing values:
df.isnull().sum()
df.dropna()
df.fillna(0)

## Role of Pandas in Machine Learning

### Before training a Machine Learning model, data must be prepared. Pandas is used in almost every ML project.

#<<<<<<<<<<<Step 1: Load Dataset
df = pd.read_csv("dataset.csv")

#<<<<<<<<<<<Step 2: Clean Data
df.fillna(df.mean(numeric_only=True), inplace=True)

#<<<<<<<<<<<Step 3: Encode Categorical Data
df = pd.get_dummies(df)

#<<<<<<<<<<<Step 4: Feature Selection
X = df.drop("Price", axis=1)
y = df["Price"]

#<<<<<<<<<<<Step 5: Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#<<<<<<<<<<<Step 6: Model Training
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

2. Differentiate between: 
● Series and DataFrame  
● loc[] and iloc[] 
functions in Pandas

| Feature    | Series                        | DataFrame                                       |
| ---------- | ----------------------------- | ----------------------------------------------- |
| Definition | One-dimensional labeled array | Two-dimensional labeled table                   |
| Dimensions | 1D                            | 2D                                              |
| Structure  | Single column of data         | Multiple rows and columns                       |
| Data Types | Usually one data type         | Different columns can have different data types |
| Index      | Has an index                  | Has both row index and column names             |
| Example    | Marks of students             | Complete student record                         |

| Feature         | loc[]                             | iloc[]                              |
| --------------- | --------------------------------- | ----------------------------------- |
| Selection Basis | Label (name) based                | Integer position based              |
| Rows/Columns    | Uses row and column labels        | Uses row and column index positions |
| End Index       | Included                          | Excluded (Python slicing rule)      |
| Syntax          | `df.loc[row_label, column_label]` | `df.iloc[row_index, column_index]`  |

 3. Create a Pandas DataFrame using the dataset below:  Name Age Marks Amit 20 85 Neha 21 90 Rahul 19 78 Sneha 22 88  
 a) Tasks: 
 ● Display first 2 rows  
 ● Display only Name and Marks columns  
 ● Add a new column named “Result”  
 ● Display students with marks greater than 80   
 b) Expected Concepts: 
 ● pd.DataFrame()  ● head()  ● Column Selection  ● Conditional Filtering

In [59]:
data = {
    "Name" : ["Amit","Neha","Rahul","Sneha"],
    "Marks" : [85, 90, 78, 88],
    "Age" :   [20, 21, 19, 22]
}

df = pd.DataFrame(data)

df

    Name  Marks  Age
0   Amit     85   20
1   Neha     90   21
2  Rahul     78   19
3  Sneha     88   22

In [60]:
print(df.head(2))

   Name  Marks  Age
0  Amit     85   20
1  Neha     90   21

In [61]:
print(df[["Name","Marks"]])

    Name  Marks
0   Amit     85
1   Neha     90
2  Rahul     78
3  Sneha     88

In [62]:
df["Result"] = ["Pass", "Pass", "Pass", "Pass"]
df

    Name  Marks  Age Result
0   Amit     85   20   Pass
1   Neha     90   21   Pass
2  Rahul     78   19   Pass
3  Sneha     88   22   Pass

In [63]:
df[df["Marks"] > 80]

    Name  Marks  Age Result
0   Amit     85   20   Pass
1   Neha     90   21   Pass
3  Sneha     88   22   Pass

1. pd.DataFrame()

Used to create a DataFrame.

df = pd.DataFrame(data)

2. head()

Displays the first rows of a DataFrame.

df.head(2)

3. Column Selection

Select specific columns.

df[["Name", "Marks"]]

4. Conditional Filtering

Filter rows based on a condition.

df[df["Marks"] > 80]

  4. Create a DataFrame using the dataset below:
   Name A B C D 
   a) Tasks: Age 25 NaN 27 24 
   ● Identify missing values  Salary 30000 40000 NaN 35000 
   ● Fill missing Age with average age  
   ● Fill missing Salary with median salary  
   ● Display cleaned dataset  
   b) Expected Concepts: 
   ● isnull()  ● fillna()  ● mean()  ● median()

| Function   | Purpose                 |
| ---------- | ----------------------- |
| `isnull()` | Detect missing values   |
| `fillna()` | Fill missing values     |
| `mean()`   | Calculate average value |
| `median()` | Calculate middle value  |

In [64]:
data = {
      "Name": ["A", "B", "C", "D"],
    "Age": [25, np.nan , 27, 24],
    "Salary": [30000, 40000, np.nan , 35000]
}

df = pd.DataFrame(data)
print("Original Dataset:")
print(df)

Original Dataset:
  Name   Age   Salary
0    A  25.0  30000.0
1    B   NaN  40000.0
2    C  27.0      NaN
3    D  24.0  35000.0

In [65]:
#Identify Missing Values
df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False

In [66]:
df.isnull().sum()

Name      0
Age       1
Salary    1
dtype: int64

In [67]:
avg_age = df["Age"].mean()
print(avg_age)

25.333333333333332

In [68]:
# Fill Missing Age
df["Age"] = df["Age"].fillna(avg_age)

In [76]:
median_salary = df["Salary"].median()
print(median_salary)

35000.0

In [74]:
df["Salary"] = df["Salary"].fillna(median_salary)

In [75]:
print(df)

  Name        Age   Salary
0    A  25.000000  30000.0
1    B  25.333333  40000.0
2    C  27.000000  35000.0
3    D  24.000000  35000.0

5. Dataset Link: Iris Dataset 
a) Tasks: 
● Load CSV file using Pandas  
● Display dataset information  
● Find:  
o Total rows and columns  
o Average sepal length  
o Different species names  
● Display summary statistics  
b) Expected Concepts: 
● pd.read_csv()  
● info()  
● describe()  
● unique()

| Function        | Purpose                           |
| --------------- | --------------------------------- |
| `pd.read_csv()` | Load CSV file into DataFrame      |
| `info()`        | Display dataset information       |
| `shape`         | Get rows and columns count        |
| `mean()`        | Calculate average                 |
| `unique()`      | Show unique values                |
| `nunique()`     | Count the number of unique values |
| `describe()`    | Generate statistical summary      |

In [78]:
df = pd.read_csv("Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

In [80]:
print("Rows and Columns:-",df.shape)

Rows and Columns:- (150, 6)

In [89]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [92]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='str')

In [83]:
df.shape[0]

150

In [82]:
df.shape[1]

6

In [100]:
df["Species"].unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [101]:
df["Species"].nunique()

3

In [102]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000