In [6]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [7]:
df = pd.read_csv(r'Data//laptop_price.csv',encoding = 'latin-1'
)
df

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00

In [8]:
df.shape

(1303, 13)

In [9]:
df.dtypes

laptop_ID             int64
Company                 str
Product                 str
TypeName                str
Inches              float64
ScreenResolution        str
Cpu                     str
Ram                     str
Memory                  str
Gpu                     str
OpSys                   str
Weight                  str
Price_euros         float64
dtype: object

In [10]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   str
 2   Product           1303 non-null   str
 3   TypeName          1303 non-null   str
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   str
 6   Cpu               1303 non-null   str
 7   Ram               1303 non-null   str
 8   Memory            1303 non-null   str
 9   Gpu               1303 non-null   str
 10  OpSys             1303 non-null   str
 11  Weight            1303 non-null   str
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), str(10)
memory usage: 132.5 KB
None

In [11]:
df.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [12]:
(df.isnull().sum()/len(df))*100

laptop_ID           0.0
Company             0.0
Product             0.0
TypeName            0.0
Inches              0.0
ScreenResolution    0.0
Cpu                 0.0
Ram                 0.0
Memory              0.0
Gpu                 0.0
OpSys               0.0
Weight              0.0
Price_euros         0.0
dtype: float64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df.drop('laptop_ID',axis=1,inplace=True)
df.drop

<bound method DataFrame.drop of      Company                              Product            TypeName  Inches  \
0      Apple                          MacBook Pro           Ultrabook    13.3
1      Apple                          Macbook Air           Ultrabook    13.3
2         HP                               250 G6            Notebook    15.6
3      Apple                          MacBook Pro           Ultrabook    15.4
4      Apple                          MacBook Pro           Ultrabook    13.3
...      ...                                  ...                 ...     ...
1298  Lenovo                       Yoga 500-14ISK  2 in 1 Convertible    14.0
1299  Lenovo                       Yoga 900-13ISK  2 in 1 Convertible    13.3
1300  Lenovo                   IdeaPad 100S-14IBR            Notebook    14.0
1301      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon            Notebook    15.6
1302    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)            Notebook    15.6

                                ScreenResolution  \
0             IPS Panel Retina Display 2560x1600
1                                       1440x900
2                              Full HD 1920x1080
3             IPS Panel Retina Display 2880x1800
4             IPS Panel Retina Display 2560x1600
...                                          ...
1298   IPS Panel Full HD / Touchscreen 1920x1080
1299  IPS Panel Quad HD+ / Touchscreen 3200x1800
1300                                    1366x768
1301                                    1366x768
1302                                    1366x768

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD
3                     Intel Core i7 2.7GHz  16GB            512GB SSD
4                     Intel Core i5 3.1GHz   8GB            256GB SSD
...                                    ...   ...                  ...
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD

                               Gpu       OpSys  Weight  Price_euros
0     Intel Iris Plus Graphics 640       macOS  1.37kg      1339.69
1           Intel HD Graphics 6000       macOS  1.34kg       898.94
2            Intel HD Graphics 620       No OS  1.86kg       575.00
3               AMD Radeon Pro 455       macOS  1.83kg      2537.45
4     Intel Iris Plus Graphics 650       macOS  1.37kg      1803.60
...                            ...         ...     ...          ...
1298         Intel HD Graphics 520  Windows 10   1.8kg       638.00
1299         Intel HD Graphics 520  Windows 10   1.3kg      1499.00
1300             Intel HD Graphics  Windows 10   1.5kg       229.00
1301            AMD Radeon R5 M330  Windows 10  2.19kg       764.00
1302             Intel HD Graphics  Windows 10   2.2kg       369.00

[1303 rows x 12 columns]>

In [16]:
df=df.drop_duplicates()

In [17]:
for col in df.columns:
    print("\ncolumn:",col)
    print(df[col].unique())

column: Company
<StringArray>
[    'Apple',        'HP',      'Acer',      'Asus',      'Dell',    'Lenovo',
     'Chuwi',       'MSI', 'Microsoft',   'Toshiba',    'Huawei',    'Xiaomi',
      'Vero',     'Razer',  'Mediacom',   'Samsung',    'Google',   'Fujitsu',
        'LG']
Length: 19, dtype: str

column: Product
<StringArray>
[                              'MacBook Pro',
                               'Macbook Air',
                                    '250 G6',
                                  'Aspire 3',
                           'ZenBook UX430UN',
                                   'Swift 3',
                             'Inspiron 3567',
                               'MacBook 12"',
                         'IdeaPad 320-15IKB',
                                    'XPS 13',
 ...
                               'GE62 Apache',
                            'Yoga 500-14IBD',
                      'ZenBook UX305CA-UBM1',
                            'Aspire ES1-531',
                       'Pavilion 15-AW003nv',
                          'Stream 11-Y000na',
 'X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce',
                            'Yoga 500-14ISK',
       '15-AC110nv (i7-6500U/6GB/1TB/Radeon',
       'X553SA-XX031T (N3050/4GB/500GB/W10)']
Length: 618, dtype: str

column: TypeName
<StringArray>
[         'Ultrabook',           'Notebook',            'Netbook',
             'Gaming', '2 in 1 Convertible',        'Workstation']
Length: 6, dtype: str

column: Inches
[13.3 15.6 15.4 14.  12.  11.6 17.3 10.1 13.5 12.5 13.  18.4 13.9 12.3
 17.  15.  14.1 11.3]

column: ScreenResolution
<StringArray>
[           'IPS Panel Retina Display 2560x1600',
                                      '1440x900',
                             'Full HD 1920x1080',
            'IPS Panel Retina Display 2880x1800',
                                      '1366x768',
                   'IPS Panel Full HD 1920x1080',
            'IPS Panel Retina Display 2304x1440',
     'IPS Panel Full HD / Touchscreen 1920x1080',
               'Full HD / Touchscreen 1920x1080',
              'Touchscreen / Quad HD+ 3200x1800',
               'IPS Panel Touchscreen 1920x1200',
                         'Touchscreen 2256x1504',
              'Quad HD+ / Touchscreen 3200x1800',
                            'IPS Panel 1366x768',
 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
                   'IPS Panel Full HD 2160x1440',
           '4K Ultra HD / Touchscreen 3840x2160',
                         'Touchscreen 2560x1440',
                                      '1600x900',
               'IPS Panel 4K Ultra HD 3840x2160',
                         '4K Ultra HD 3840x2160',
                          'Touchscreen 1366x768',
                    'IPS Panel Full HD 1366x768',
                           'IPS Panel 2560x1440',
                   'IPS Panel Full HD 2560x1440',
            'IPS Panel Retina Display 2736x1824',
                         'Touchscreen 2400x1600',
                                     '2560x1440',
                  'IPS Panel Quad HD+ 2560x1440',
                  'IPS Panel Quad HD+ 3200x1800',
    'IPS Panel Quad HD+ / Touchscreen 3200x1800',
                'IPS Panel Touchscreen 1366x768',
                                     '1920x1080',
                   'IPS Panel Full HD 1920x1200',
 'IPS Panel Touchscreen / 4K Ultra HD 3840x2160',
               'IPS Panel Touchscreen 2560x1440',
               'Touchscreen / Full HD 1920x1080',
                            'Quad HD+ 3200x1800',
           'Touchscreen / 4K Ultra HD 3840x2160',
               'IPS Panel Touchscreen 2400x1600']
Length: 40, dtype: str

column: Cpu
<StringArray>
[                'Intel Core i5 2.3GHz',
                 'Intel Core i5 1.8GHz',
           'Intel Core i5 7200U 2.5GHz',
                 'Intel Core i7 2.7GHz',
                 'Intel Core i5 3.1GHz',
              'AMD A9-Series 9420 3GHz',
                 'Intel Core i7 2.2GHz',
           'Intel Core i7 8550U 1.8GHz',
           'Intel Core i5 8250U 1.6GHz',
             'Intel Core i3 6006U 2GHz',
 ...
                  'Intel Core M 1.1GHz',
 'Intel Pentium Dual Core 4405Y 1.5GHz',
 'Intel Pentium Quad Core N3700 1.6GHz',
             'Intel Core M 6Y54 1.1GHz',
          'Intel Core i7 6500U 2.50GHz',
   'Intel Celeron Dual Core N3350 2GHz',
        'Samsung Cortex A72&A53 2.0GHz',
             'AMD E-Series 9000 2.2GHz',
             'Intel Core M 6Y30 0.9GHz',
            'AMD A9-Series 9410 2.9GHz']
Length: 118, dtype: str

column: Ram
<StringArray>
['8GB', '16GB', '4GB', '2GB', '12GB', '6GB', '32GB', '24GB', '64GB']
Length: 9, dtype: str

column: Memory
<StringArray>
[                    '128GB SSD',           '128GB Flash Storage',
                     '256GB SSD',                     '512GB SSD',
                     '500GB HDD',           '256GB Flash Storage',
                       '1TB HDD',            '32GB Flash Storage',
          '128GB SSD +  1TB HDD',        '256GB SSD +  256GB SSD',
            '64GB Flash Storage',          '256GB SSD +  1TB HDD',
          '256GB SSD +  2TB HDD',                      '32GB SSD',
                       '2TB HDD',                      '64GB SSD',
                  '1.0TB Hybrid',          '512GB SSD +  1TB HDD',
                       '1TB SSD',        '256GB SSD +  500GB HDD',
          '128GB SSD +  2TB HDD',        '512GB SSD +  512GB SSD',
                      '16GB SSD',            '16GB Flash Storage',
        '512GB SSD +  256GB SSD',          '512GB SSD +  2TB HDD',
 '64GB Flash Storage +  1TB HDD',                     '180GB SSD',
            '1TB HDD +  1TB HDD',                      '32GB HDD',
            '1TB SSD +  1TB HDD',           '512GB Flash Storage',
                     '128GB HDD',                     '240GB SSD',
                       '8GB SSD',                  '508GB Hybrid',
                     '1.0TB HDD',     '512GB SSD +  1.0TB Hybrid',
     '256GB SSD +  1.0TB Hybrid']
Length: 39, dtype: str

column: Gpu
<StringArray>
['Intel Iris Plus Graphics 640',       'Intel HD Graphics 6000',
        'Intel HD Graphics 620',           'AMD Radeon Pro 455',
 'Intel Iris Plus Graphics 650',                'AMD Radeon R5',
      'Intel Iris Pro Graphics',         'Nvidia GeForce MX150',
       'Intel UHD Graphics 620',        'Intel HD Graphics 520',
 ...
      'Nvidia GeForce GTX 980 ',           'AMD Radeon R5 M330',
           'AMD FirePro W4190M',           'AMD FirePro W6150M',
           'AMD Radeon R5 M315',          'Nvidia Quadro M500M',
           'AMD Radeon R7 M360',         'Nvidia Quadro M3000M',
          'Nvidia GeForce 960M',            'ARM Mali T860 MP4']
Length: 110, dtype: str

column: OpSys
<StringArray>
[       'macOS',        'No OS',   'Windows 10',     'Mac OS X',
        'Linux',      'Android', 'Windows 10 S',    'Chrome OS',
    'Windows 7']
Length: 9, dtype: str

column: Weight
<StringArray>
[ '1.37kg',  '1.34kg',  '1.86kg',  '1.83kg',   '2.1kg',  '2.04kg',   '1.3kg',
   '1.6kg',   '2.2kg',  '0.92kg',
 ...
     '4kg',   '3.0kg',  '0.99kg',  '3.52kg', '2.591kg',  '2.21kg',   '3.3kg',
 '2.191kg',  '2.34kg',   '4.0kg']
Length: 179, dtype: str

column: Price_euros
[1339.69  898.94  575.   2537.45 1803.6   400.   2139.97 1158.7  1495.
  770.    393.9   344.99 2439.97  498.9  1262.4  1518.55  745.   2858.
  499.    979.    191.9   999.    258.    819.    659.    418.64 1099.
  800.   1298.    896.    244.99  199.    439.   1869.    998.    249.
  367.    488.69  879.    389.   1499.    522.99  682.   1419.    369.
 1299.    639.    466.    319.    841.    398.49 1103.    384.    767.8
  586.19 2449.    415.    599.    941.    690.   1983.    438.69  229.
  549.    949.   1089.    955.    870.   1095.    519.    855.    530.
  977.   1096.16 1510.    860.    399.    395.   1349.    699.    598.99
 1449.   1649.    689.   1197.   1195.   1049.    847.    599.9   485.
  577.   1249.    719.    349.    647.   1119.   1340.    414.9  1193.
 1480.   1262.   1379.   1399.    722.   1629.   1398.99 1084.   1130.33
  564.   1118.    479.   2241.5   629.   1271.    451.    259.    812.
  277.99 1396.    928.    638.99  449.    884.    572.    598.    988.
  252.36  938.    655.   1116.02  869.    602.   2014.    344.   2029.
  447.   1249.26  899.    498.   1890.   1082.    619.   1315.    403.
  805.    728.   1079.    348.   1799.    363.51 1060.49  854.    754.
  309.    489.    923.    459.   2799.    813.   1849.    793.   1199.
 1549.   2397.    779.    989.   1085.   2824.    260.    999.9   698.
  839.    914.   6099.    959.   1045.   1845.    493.    742.   1749.
 3055.   1398.   1949.    597.   1407.    931.88  589.   1031.   1149.
 1279.    677.35 1363.    794.   2456.34  832.    859.01  769.    891.
 1269.    398.99  330.    859.    390.   3890.    846.   1145.    889.
  985.    559.   2999.    675.   2040.    469.    702.    445.9  1059.
 2499.   1699.   1142.    444.    657.    565.    799.    467.   1018.
  880.   1958.9   735.07  713.07  849.    428.    829.    579.    951.
 1097.   1179.    659.01 1187.   1829.    739.   2884.86 1468.    509.
 2122.    649.   1265.    359.99 1975.   1043.   2099.    275.    844.
  459.9   980.   1292.   1094.    902.    292.   1049.9  1335.   2639.
  943.   1334.   1268.   1144.    274.99 1142.75  274.9   716.   1579.
 1129.    279.   1607.96  375.    663.   2027.42 1304.   1409.   1738.27
 1403.    970.9   321.99  557.37 1427.    945.    809.   1750.    426.
 2199.    869.01  488.99  553.    286.   1191.    403.5  1655.   1748.9
 2282.   1369.   2135.   2509.   1039.   1591.    693.99  778.87 1229.56
 2712.   2625.    306.   1529.   1144.5  2249.   1873.   1747.   1680.
  409.    304.45 1925.   1943.    789.01  598.9  1500.    539.95 1215.38
 1899.   1159.   1142.4  1999.    299.    269.   1010.   2445.   1695.
  347.   2382.    749.   1429.    441.8  1993.   1027.74 2589.   1534.
 1345.   2046.    639.9   544.    435.   2090.    304.    759.   1858.
 1154.   1275.   1841.85  740.   2408.   1364.   1672.    586.6   726.
  248.9  2338.   1798.   1950.   1011.99 1350.    898.9   911.    340.
  618.99 1599.    265.   1224.    613.   1323.    836.   1219.24 1399.95
  245.    521.47 2968.   1504.   1279.73  585.   1377.   3012.77  797.41
  735.87  798.    705.5   785.    462.35  397.   1729.   1116.99 2699.
  544.15 1280.    224.    255.    568.9   617.9   630.   1965.    990.
 1860.99  830.    685.   1865.   2663.   2729.    749.01 1008.52 1537.39
  295.   2349.   1498.   1673.    609.   1770.    603.    529.   2025.
 1474.   1670.   1763.   1219.    668.48  329.    465.   2299.   4899.
  879.01  443.9   359.   1168.    569.   1389.   2267.86  379.   1124.
 1465.    776.    932.    239.    468.    639.01 1820.   1900.   1479.
  906.62 1757.42 2399.   1109.    520.9  2450.   1169.    450.    274.
  919.   2599.   1213.   1584.    709.   1449.9  1191.8   364.9  1064.
 1135.   1196.   3147.37 1229.    419.    535.    539.   1486.77 1258.
  412.   1867.85  817.95 1034.   1294.    495.    997.9  2051.   2813.75
  612.61  545.67  318.   1907.99 2590.    973.    669.   1877.    429.
  621.45  795.   1855.    655.01  298.   1426.66  857.07 1200.   1686.64
  836.6  3659.4  1348.48  489.9   589.52 1935.    650.    960.   2419.
 2094.48  410.8  1207.    665.   1535.   3299.   1126.71 4389.    475.
 1096.    849.9  1561.   2868.99 1048.   1859.   1559.    470.34 1181.27
 1020.   1244.   2370.    636.   2899.    581.9  3588.8  2350.   1764.
 1891.   1339.    202.9  1970.   1165.   2330.    810.   2064.9   744.
  780.   1679.   2415.    961.    789.81  385.   2505.02  755.   1090.
 1875.   1358.    355.   5499.   1186.   1650.   2774.63  325.    590.
 3072.89  910.    713.99 1870.    615.   1026.   2277.    865.   1903.
  787.   2559.    850.66 1285.   1017.   2240.   1778.   1055.   1388.
  735.   1690.    935.    912.5  1700.    684.8   455.7  1369.9   297.
 2649.   1475.    929.    900.    614.   2013.1  2049.   1962.99 1483.
  789.   1205.   3100.   1018.99  881.   1119.91  684.99 1296.99 1825.
  729.9   708.06  288.9  1105.   1669.    558.6  1639.   2758.   1472.2
 1775.   1460.   1488.99 3154.    775.   1760.   1009.   1790.    846.5
  465.62  825.   3149.    695.   1962.98 2800.   1180.   2049.9  1002.
  915.    806.   1189.   1908.    270.62 1150.    380.   2089.   1260.
  547.   1099.99 1049.26  684.   1539.   1590.   1887.21 1210.    769.99
 1490.   2229.    795.99 1185.43 1046.44 1060.   1624.   1080.   1228.99
 1725.   1062.95 1010.51  210.8  1425.   1049.6  1000.   2103.34 1469.
 1545.64 2289.99  287.9  2620.   2254.    705.15 1819.   1070.    989.99
 1929.   1458.   3975.    798.01 1329.   1300.    481.98 1713.49  540.
  940.   3240.    646.27  750.   1030.99  387.    393.49  345.99  818.35
  638.8   500.   1135.15 1166.97  209.   1413.1  1511.19  867.    398.
  769.15 1969.   2749.99 1029.   2226.   1312.49  196.   1513.    523.63
 1895.   2050.38  278.    752.    616.   3949.4   784.   2171.72 2440.
 1142.8  2296.95 1009.9  2339.    339.   2250.68  478.89 1492.8   788.49
 2041.   1769.    476.99 1390.    679.   1305.   2153.37 1637.    831.
  895.01  333.    909.    691.   1163.   1327.    368.   2150.    272.
 2048.9  2680.   1948.99  174.   1272.   1476.11 1713.37 1477.    521.86
 3499.    469.01 1598.    478.   2198.19  737.    597.57  361.8  1600.
  875.   2325.    573.   1813.    324.   1072.    443.99  490.    895.
  833.01  729.    289.    549.99  805.99  720.32  638.    764.  ]

In [18]:
Company_list = df['Company'].unique().tolist()
Company_dict = {Company: i+1 for i, Company in enumerate(Company_list)}
print(Company_dict)
df['Company'] = df['Company'].map(Company_dict)

{'Apple': 1, 'HP': 2, 'Acer': 3, 'Asus': 4, 'Dell': 5, 'Lenovo': 6, 'Chuwi': 7, 'MSI': 8, 'Microsoft': 9, 'Toshiba': 10, 'Huawei': 11, 'Xiaomi': 12, 'Vero': 13, 'Razer': 14, 'Mediacom': 15, 'Samsung': 16, 'Google': 17, 'Fujitsu': 18, 'LG': 19}

In [19]:
Product_list = df['Product'].unique().tolist()
Product_dict = {Product: i+1 for i, Product in enumerate(Product_list)}
print(Product_dict)
df['Product'] = df['Product'].map(Product_dict)

{'MacBook Pro': 1, 'Macbook Air': 2, '250 G6': 3, 'Aspire 3': 4, 'ZenBook UX430UN': 5, 'Swift 3': 6, 'Inspiron 3567': 7, 'MacBook 12"': 8, 'IdeaPad 320-15IKB': 9, 'XPS 13': 10, 'Vivobook E200HA': 11, 'Legion Y520-15IKBN': 12, '255 G6': 13, 'Inspiron 5379': 14, '15-BS101nv (i7-8550U/8GB/256GB/FHD/W10)': 15, 'MacBook Air': 16, 'Inspiron 5570': 17, 'Latitude 5590': 18, 'ProBook 470': 19, 'LapBook 15.6"': 20, 'E402WA-GA010T (E2-6110/2GB/32GB/W10)': 21, '17-ak001nv (A6-9220/4GB/500GB/Radeon': 22, 'IdeaPad 120S-14IAP': 23, 'Inspiron 5770': 24, 'ProBook 450': 25, 'X540UA-DM186 (i3-6006U/4GB/1TB/FHD/Linux)': 26, 'Inspiron 7577': 27, 'X542UQ-GO005 (i5-7200U/8GB/1TB/GeForce': 28, 'Aspire A515-51G': 29, 'Inspiron 7773': 30, 'IdeaPad 320-15ISK': 31, 'Rog Strix': 32, 'X751NV-TY001T (N4200/4GB/1TB/GeForce': 33, 'Yoga Book': 34, 'ProBook 430': 35, 'Inspiron 3576': 36, '15-bs002nv (i3-6006U/4GB/128GB/FHD/W10)': 37, 'VivoBook Max': 38, 'GS73VR 7RG': 39, 'X541UA-DM1897 (i3-6006U/4GB/256GB/FHD/Linux)': 40, 'Vostro 5471': 41, 'IdeaPad 520S-14IKB': 42, 'UX410UA-GV350T (i5-8250U/8GB/256GB/FHD/W10)': 43, 'ZenBook Pro': 44, 'Stream 14-AX040wm': 45, 'V310-15ISK (i5-7200U/4GB/1TB/FHD/W10)': 46, 'FX753VE-GC093 (i7-7700HQ/12GB/1TB/GeForce': 47, 'Surface Laptop': 48, 'Inspiron 5370': 49, 'GL72M 7RDX': 50, 'Aspire E5-475': 51, 'FX503VD-E4022T (i7-7700HQ/8GB/1TB/GeForce': 52, 'IdeaPad 320-15IKBN': 53, 'Aspire A515-51G-32MX': 54, 'ProBook 440': 55, 'IdeaPad 320-15AST': 56, 'Pavilion 15-CK000nv': 57, 'FX503VM-E4007T (i7-7700HQ/16GB/1TB': 58, 'FX550IK-DM018T (FX-9830P/8GB/1TB/Radeon': 59, 'Aspire 5': 60, 'Probook 430': 61, 'Zenbook UX430UA': 62, 'Spin 5': 63, 'X541UV-DM1439T (i3-7100U/6GB/256GB/GeForce': 64, 'Omen 15-ce007nv': 65, '15-bs017nv (i7-7500U/8GB/256GB/Radeon': 66, '15-bw000nv (E2-9000e/4GB/500GB/Radeon': 67, 'Envy 13-ad009n': 68, 'Pavilion 14-BK001nv': 69, 'Ideapad 310-15ISK': 70, 'UX430UQ-GV209R (i7-7500U/8GB/256GB/GeForce': 71, 'GP62M 7REX': 72, 'Thinkpad T470': 73, 'VivoBook S15': 74, 'ThinkPad Yoga': 75, 'Probook 440': 76, 'Spectre x360': 77, 'Inspiron 7570': 78, 'X705UV-BX074T (i3-6006U/4GB/1TB/GeForce': 79, 'Spin 3': 80, 'GS63VR 7RG': 81, 'Probook 470': 82, 'E402WA-GA007T (E2-6110/4GB/64GB/W10': 83, 'Inspiron 5567': 84, 'Aspire A515-51G-37JS': 85, '15-BS078nr (i7-7500U/8GB/1TB/W10)': 86, 'V110-15IAP (N3350/4GB/1TB/No': 87, 'FX753VD-GC086T (i5-7300HQ/8GB/1TB': 88, 'Envy 13-AD007nv': 89, 'ThinkPad E480': 90, 'Satellite Pro': 91, 'ZenBook UX430UA': 92, 'EliteBook Folio': 93, 'X541NA (N3350/4GB/1TB/FHD/W10)': 94, 'GE72MVR 7RG': 95, 'Aspire A315-51': 96, 'Inspiron 5577': 97, 'Inspiron 7567': 98, 'V110-15IKB (i5-7200U/4GB/128GB/W10)': 99, 'GE73VR 7RE': 100, 'EliteBook 840': 101, '15-BS103nv (i5-8250U/6GB/256GB/Radeon': 102, 'Yoga 520-14IKB': 103, 'ZenBook Flip': 104, 'Inspiron 5579': 105, 'X555BP-XX180T (A9-9420/4GB/1TB/Radeon': 106, 'Aspire A517-51G': 107, 'Aspire A315-31': 108, 'GE63VR 7RE': 109, 'MateBook X': 110, '17-bs001nv (i5-7200U/6GB/2TB/Radeon': 111, 'GT80S 6QF-074US': 112, 'V310-15IKB (i5-7200U/8GB/1TB': 113, 'Yoga 920-13IKB': 114, 'Mi Notebook': 115, 'XPS 15': 116, 'Swift 7': 117, 'Thinkpad Yoga': 118, 'K147 (N3350/4GB/32GB/FHD/W10)': 119, 'IdeaPad 320-17IKBR': 120, 'Blade Pro': 121, 'Omen 17-W295': 122, 'V110-15ISK (i5-6200U/4GB/128GB/W10)': 123, 'Aspire E5-576G': 124, 'Legion Y720-15IKB': 125, 'Precision 7520': 126, 'Aspire 7': 127, 'ROG GL703VD-GC028T': 128, '15-bs018nq (i3-6006U/4GB/500GB/FHD/No': 129, 'IdeaPad 320-17IKB': 130, 'Latitude 5490': 131, 'Portege Z30-C-16L': 132, 'Alienware 17': 133, 'Vivobook X541UV-DM1217T': 134, 'K756UX-T4340T (i5-7200U/8GB/500GB': 135, 'ZBook 15u': 136, 'Pro P2540UA-XO0198T': 137, '15-rb013nv (E2-9000e/4GB/500GB/W10)': 138, 'Vostro 5468': 139, 'Aspire R7': 140, 'X555QG-DM242T (A10-9620P/4GB/1TB': 141, 'ROG G703VI-E5062T': 142, 'Nitro AN515-51': 143, 'VivoBook Pro': 144, 'F756UX-T4201D (i7-7500U/8GB/128GB': 145, 'Yoga 910-13IKB': 146, '15-bs015dx (i5-7200U/8GB/1TB/W10)': 147, 'Rog G701VIK-BA060T': 148, 'ROG G752VSK-GC493T': 149, 'X505BP-BR019T (A9-9420/4GB/1TB/Radeon': 150, 'Vostro 5370': 151, '15-BW094nd (A6-9220/8GB/128GB/W10)': 152, 'Envy 17-U275cl': 153, 'GT73EVR 7RE': 154, 'Yoga 720-15IKB': 155, 'Vostro 3568': 156, 'V330-15IKB (i7-8550U/8GB/256GB/FHD/W10)': 157, 'ThinkPad X1': 158, 'IdeaPad 320-17ISK': 159, 'Ideapad 320-15IKBN': 160, 'SP315-51 (i7-7500U/12GB/1TB/FHD/W10)': 161, 'Thinkpad T570': 162, 'Chromebook C910-C2ST': 163, 'FX753VD-GC071T (i7-7700HQ/8GB/1TB/GeForce': 164, '17-BS037cl (i3-6006U/8GB/1TB/W10)': 165, 'V330-15IKB (i5-8250U/8GB/256GB/FHD/W10)': 166, 'Aspire A715-71G': 167, 'Precision 7720': 168, 'IdeaPad 310-15ABR': 169, 'ZenBook UX530UQ-PRO': 170, 'VivoBook S14': 171, 'Rog GL702VS-GC095T': 172, 'GL553VE-FY082T (i7-7700HQ/8GB/1TB': 173, 'IdeaPad 320-15IAP': 174, 'EliteBook x360': 175, 'IdeaPad 720S-13IKB': 176, 'GE63VR 7RF': 177, 'ES1-523-84K7 (A8-7410/8GB/256GB/FHD/W10)': 178, 'VivoBook Flip': 179, 'ThinkPad 13': 180, 'ProBook 640': 181, 'TravelMate B': 182, 'Elitebook 840': 183, 'ZenBook UX410UA-GV183T': 184, 'Aspire E5-575': 185, 'Elitebook 820': 186, 'GL72M 7REX': 187, 'UX510UX-CN269T (i7-7500U/8GB/256GB': 188, 'V310-15ISK (i3-6006U/4GB/1TB/FHD/W10)': 189, 'FX553VD-FY647T (i7-7700HQ/8GB/256GB/GeForce': 190, 'Elitebook 850': 191, 'X541NA (N3350/4GB/1TB/Linux)': 192, 'Inspiron 3552': 193, 'IdeaPad 320-15ABR': 194, 'Stream 14-AX001nv': 195, 'GP72MVR 7RFX': 196, 'Zbook 15': 197, 'Tecra A50-C-21G': 198, 'Latitude 7480': 199, 'Zenbook UX410UA-GV027T': 200, '15-AY023na (N3710/8GB/2TB/W10)': 201, 'Elitebook 1040': 202, 'IdeaPad 110-17ACL': 203, '15-bw003nv (A9-Series-9420/4GB/256GB/FHD/W10)': 204, 'Yoga 11e': 205, 'VivoBook E403NA': 206, 'Omen 17-w212nv': 207, 'V310-15ISK (i3-6006U/4GB/128GB/FHD/No': 208, 'ROG Strix': 209, 'IdeaPad 720S-14IKB': 210, 'Zenbook Flip': 211, 'Thinkpad X1': 212, 'Ideapad 510S-13IKB': 213, 'Precision 3510': 214, 'Precision 5520': 215, 'Rog GL753VD-GC042T': 216, 'Rog GL753VE-GC070T': 217, 'Leopard GP72M': 218, '15-BW004nv (A9-9420/4GB/256GB/Radeon': 219, 'ThinkPad E580': 220, 'ThinkPad L470': 221, 'Precision M5520': 222, 'FX753VD-GC461T (i7-7700HQ/16GB/1TB': 223, 'GE73VR 7RF': 224, 'Zenbook 3': 225, 'Portege Z30-C-16P': 226, 'Lenovo IdeaPad': 227, 'ThinkPad P51': 228, 'Thinkpad T470p': 229, '15-BS028nv (i3-6006U/4GB/1TB/Radeon': 230, 'Latitude 3380': 231, 'EliteBook 1040': 232, 'LapBook 12.3': 233, 'ProBook 650': 234, 'X542UQ-DM117 (i3-7100U/8GB/1TB/GeForce': 235, 'Latitude 5480': 236, 'Omen 17-w207nv': 237, 'FlexBook Edge': 238, 'Chromebook 3': 239, 'Thinkpad 13': 240, 'IdeaPad 320s-14IKB': 241, 'Thinkpad P51': 242, '15-ra044nv (N3060/4GB/500GB/W10)': 243, 'Pixelbook (Core': 244, 'ThinkPad T470s': 245, 'ThinkPad X270': 246, 'Omen 15-AX205na': 247, 'Aspire ES1-572': 248, 'Precision 3520': 249, 'GV62 7RD-1686NL': 250, '15-bs024nv (i5-7200U/8GB/128GB/W10)': 251, 'ThinkPad T470': 252, 'Inspiron 3168': 253, '17-BS092ND (i3-6006U/8GB/256GB/W10)': 254, 'Pro P2540UA-AB51': 255, 'IdeaPad 510s-14IKB': 256, 'X541NA-PD1003Y (N4200/4GB/500GB/W10)': 257, 'Omen 17-an006nv': 258, 'Thinkpad T460s': 259, 'Latitude 7390': 260, 'Latitude E5470': 261, 'Portege X30-D-10J': 262, 'Lapbook 15,6': 263, 'ThinkPad E570': 264, 'Thinkpad X270': 265, 'Zenbook UX390UA': 266, 'Thinkpad E570': 267, 'Portege X30-D-10L': 268, 'Rog G752VL-UH71T': 269, 'Thinkpad X260': 270, 'Ideapad 520-15IKBR': 271, 'ThinkPad L570': 272, 'VivoBook E201NA': 273, '15-BS026nv (i5-7200U/8GB/256GB/Radeon': 274, 'IdeaPad 320-14IAP': 275, 'Chromebook N23': 276, 'ZenBook UX510UX-CN211T': 277, 'Aspire A515-51G-59QF': 278, 'Envy 13-AB002nv': 279, 'Vostro 5568': 280, 'VivoBook E12': 281, '15-bs190od (i5-8250U/4GB/1TB/W10)': 282, 'ROG Zephyrus': 283, 'Probook 450': 284, 'FX753VE-GC155T (i7-7700HQ/16GB/1TB': 285, 'Spectre X360': 286, 'Latitude 5580': 287, 'Zenbook UX510UW-FI095T': 288, 'SmartBook Edge': 289, 'Omen 15-ce006nv': 290, 'Thinkpad E470': 291, 'Envy 13-AB020nr': 292, 'VivoBook X540YA-XX519T': 293, 'ThinkPad E470': 294, 'V310-15ISK (i5-6200U/4GB/1TB/FHD/No': 295, 'ThinkPad T570': 296, '17-X047na (i3-6006U/8GB/1TB/W10)': 297, 'A541NA-GO342 (N3350/4GB/500GB/Linux)': 298, 'SmartBook 130': 299, '15-bw007nv (A10-9620P/6GB/128GB/Radeon': 300, 'Spin SP111-31': 301, 'V330-15IKB (i3-7130U/4GB/128GB/FHD/W10)': 302, 'EliteBook 1030': 303, 'Thinkpad P71': 304, 'FX553VD-DM627T (i5-7300HQ/8GB/1TB': 305, 'Lifebook A557': 306, 'ZBook 17': 307, '14-am079na (N3710/8GB/2TB/W10)': 308, '15-cd005nv (A9-9420/6GB/256GB/Radeon': 309, 'V330-15IKB (i5-8250U/4GB/500GB/FHD/W10)': 310, 'SmartBook 141': 311, 'Tecra X40-D-10H': 312, 'IdeaPad Y910-17ISK': 313, 'GT73VR Titan': 314, 'Chromebook 11': 315, 'GT80S 6QE': 316, 'Omen 17-AN010nv': 317, 'Ideapad 320-15IKBR': 318, 'TP501UA-CJ131T (i5-7200U/8GB/1TB/W10)': 319, 'Inspiron 3179': 320, 'Notebook Odyssey': 321, 'V320-17ISK (i3-6006U/4GB/500GB/FHD/No': 322, 'IdeaPad 110-15ISK': 323, 'Latitude 5289': 324, 'EliteBook 850': 325, 'Aspire 1': 326, 'Laptop MSI': 327, 'GS63VR 7RF': 328, 'Tecra Z50-C-144': 329, 'IdeaPad 310-15IKB': 330, 'Swift SF114-31-P5HY': 331, 'Inspiron 7559': 332, 'FX753VD-GC007T (i7-7700HQ/8GB/1TB': 333, 'GT62VR 7RE': 334, 'CB5-132T-C9KK (N3160/4GB/32GB/Chrome': 335, 'LifeBook A557': 336, 'SmartBook 140': 337, 'Q304UA-BHI5T11 (i5-7200U/6GB/1TB/FHD/W10)': 338, 'ZenBook 3': 339, 'V330-15IKB (i5-8250U/4GB/256GB/FHD/W10)': 340, 'Ideapad 320-15ISK': 341, 'X541NA-GO414T (N3350/8GB/1TB/W10)': 342, 'IdeaPad 100S-14IBR': 343, '17-AK091ND (A9-9420/8GB/1TB/W10)': 344, 'ROG GL553VE-FY022': 345, 'Extensa EX2540': 346, 'Portege Z30-C-16J': 347, 'ROG G701VI': 348, 'A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce': 349, 'GL62M 7REX': 350, 'Tecra A50-D-11M': 351, 'IdeaPad Y700-15ISK': 352, 'Latitude E7470': 353, 'Ideapad 320-15IAP': 354, '15-ay047nv (i3-6006U/6GB/1TB/Radeon': 355, 'GP72VR Leopard': 356, 'Latitude 3580': 357, '15-bs012nv (i7-7500U/8GB/1TB/Radeon': 358, 'Tecra Z50-D-10E': 359, 'V310-15ISK (i5-7200U/8GB/1TB': 360, 'Yoga 720-13IKB': 361, 'Pavilion X360': 362, 'GP62 7RDX': 363, 'Chromebook X360': 364, 'Gram 15Z975': 365, 'Aspire VX5-591G': 366, 'GV62M 7RD': 367, 'L502NA-GO052T (N3350/4GB/128GB/W10)': 368, 'Alienware 15': 369, '17-bs000nv I3': 370, 'Yoga 730': 371, '17-Y002nv (A10-9600P/6GB/2TB/Radeon': 372, 'V110-15ISK (3855U/4GB/500GB/W10)': 373, 'Chromebook 14': 374, 'IdeaPad 520s-14IKB': 375, 'TravelMate B117-M': 376, 'Chromebook Flip': 377, 'Portege Z30T-C-133': 378, '15-bs011nv (i7-7500U/4GB/500GB/Radeon': 379, 'V310-15IKB (i5-7200U/4GB/1TB/FHD/W10)': 380, 'V310-15ISK (i3-6006U/4GB/500GB/No': 381, 'ThinkPad P51s': 382, 'Thinkpad T460p': 383, '17-ak002nv (A10-9620P/6GB/2TB/Radeon': 384, '110-15ACL (A6-7310/4GB/500GB/W10)': 385, 'Smartbook 142': 386, 'V310-15IKB (i5-7200U/4GB/1TB/No': 387, 'Inspiron 5378': 388, '15-BW037na (A9-9420/4GB/1TB/Radeon': 389, 'Predator 17': 390, '15-BW091ND (A9-9420/6GB/1TB': 391, 'Extensa EX2540-58KR': 392, 'V310-15IKB (i7-7500U/4GB/1TB/FHD/W10)': 393, 'ZBook 15': 394, 'Inspiron 7560': 395, 'Tecra X40-D-10G': 396, 'Flex 5': 397, 'Thinkpad P51s': 398, 'Notebook 9': 399, 'Zbook 17': 400, 'N23 (N3060/4GB/128GB/W10)': 401, 'X550VX-XX015D (i5-6300HQ/4GB/1TB/GeForce': 402, 'Thinkpad T460': 403, 'Pro P2540UA-XO0192R': 404, 'Yoga 900-13ISK': 405, '15-cb003na (i5-7300HQ/8GB/1TB': 406, 'Latitude 7280': 407, 'Zenbook UX330UA-AH5Q': 408, 'TravelMate P238-M': 409, 'X751NV-TY001 (N4200/4GB/1TB/GeForce': 410, 'Tecra A40-C-1E5': 411, 'EliteBook 820': 412, 'Q524UQ-BHI7T15 (i7-7500U/12GB/2TB/GeForce': 413, 'Thinkpad P50': 414, 'Vivobook Max': 415, 'Rog G752VS-BA171T': 416, 'Tecra Z40-C-161': 417, 'IdeaPad 110-15IBR': 418, 'GS43VR 7RE': 419, 'GL62M (i5-7300HQ/8GB/1TB': 420, 'Predator G9-793': 421, 'FX502VM-DM560T (i7-7700HQ/8GB/1TB': 422, 'K146 (N3350/4GB/32GB/W10)': 423, 'Yoga 510-15IKB': 424, 'R417NA-RS01 (N3350/4GB/32GB/W10)': 425, 'Pro P2540UA-XS51': 426, 'Latitude 3180': 427, '15-ba043na (A12-9700P/8GB/2TB/W10)': 428, 'Omen 17-an012dx': 429, 'Thinkpad T470s': 430, 'Blade Stealth': 431, 'Latitude 3480': 432, 'V110-15ISK (i3-6006U/4GB/500GB/W10)': 433, 'Tecra X40-D-10Z': 434, 'GL62M 7RD': 435, 'Rog GL702VS-BA023T': 436, 'N42-20 Chromebook': 437, 'R558UA-DM966T (i5-7200U/8GB/128GB/FHD/W10)': 438, 'Rog GL702VM-GC017T': 439, 'ZenBook UX310UQ-GL026T': 440, 'Rog GL502VM-DS74': 441, 'Inspiron 5767': 442, 'ThinkPad T470p': 443, 'K556UR-DM621T (i7-7500U/8GB/256GB/GeForce': 444, 'X541NA (N4200/4GB/1TB/W10)': 445, 'Inspiron 5368': 446, 'Portege X30-D-10X': 447, 'Portégé Z30-C-188': 448, 'TMX349-G2-M-50FS (i5-7200U/8GB/256GB/FHD/W10)': 449, 'Tecra A50-D-11D': 450, 'X541NA-GO121 (N4200/4GB/1TB/Linux)': 451, 'Pavilion x360': 452, 'VivoBook L402NA': 453, 'IdeaPad 510-15ISK': 454, 'Rog GL753VD-GC082T': 455, 'Chromebook C731-C78G': 456, 'Probook 640': 457, 'Envy x360': 458, 'GS73VR Stealth': 459, 'Portege X30-D-10V': 460, 'G701VO-IH74K (i7-6820HK/32GB/2x': 461, 'Gram 15Z970': 462, 'Chromebook CB5-571-C1DZ': 463, 'Gram 14Z970': 464, 'Elitebook Folio': 465, 'IdeaPad 510-15IKB': 466, 'GE72VR 6RF': 467, 'Envy 13-AB077cl': 468, 'Tecra Z50-C-140': 469, 'Probook 650': 470, 'Tecra Z40-C-12X': 471, 'GP62M Leopard': 472, 'Omen 17-W006na': 473, 'X751SV-TY001T (N3710/4GB/1TB/GeForce': 474, 'TravelMate P259-G2': 475, 'Tecra A50-C-1ZV': 476, 'Yoga 700-11ISK': 477, 'IdeaPad Y700-15ACZ': 478, 'Insprion 5767': 479, 'ZBook Studio': 480, 'Portege Z30-C-1CW': 481, 'ProBook x360': 482, 'Chromebook C738T-C2EJ': 483, 'Portege Z30-C-16Z': 484, 'Aspire F5-573G-510L': 485, 'Portege X20W-D-10V': 486, 'Tecra A40-C-1DF': 487, 'ThinkPad T460': 488, 'Q534UX-BHI7T19 (i7-7500U/16GB/2TB': 489, '15-bs053od (i7-7500U/6GB/1TB/W10)': 490, 'Rog GL753VE-DS74': 491, 'Inspiron 7579': 492, 'Portege Z30-C-1CV': 493, 'LifeBook A556': 494, 'Tecra A40-C-1KF': 495, '15-bs005nv (i3-6006U/4GB/1TB': 496, 'V110-15IAP (N3350/4GB/128GB/No': 497, 'ThinkPad T560': 498, 'ZenBook UX310UA-FB485T': 499, 'Spectre 13-V111dx': 500, 'Aspire ES1-533': 501, 'Rog GL553VE-DS74': 502, 'Nitro 5': 503, 'ENVY -': 504, 'Portege Z30-C-16H': 505, 'Portege A30-C-1CZ': 506, 'ThinkPad P70': 507, 'Tecra Z40-C-12Z': 508, 'Inspiron 5568': 509, 'Portégé Z30-C-16K': 510, 'Spectre 13-V100nv': 511, 'Latitude E5570': 512, 'Tecra Z40-C-136': 513, 'Yoga 500-15ISK': 514, 'V142 (X5-Z8350/2GB/32GB/W10)': 515, 'Tecra A50-C-218': 516, 'Thinkpad L560': 517, 'GT72S Dominator': 518, 'IdeaPad Y900-17ISK': 519, 'Chromebook C202SA': 520, 'Noteb Pav': 521, 'Inspiron 5578': 522, '250 G5': 523, 'Aspire ES1-523': 524, 'Inspiron 7378': 525, 'GT62VR 6RD': 526, 'Rog G752VL-GC088D': 527, 'GS63VR 6RF': 528, 'ROG G701VO': 529, 'Latitude 3570': 530, 'IdeaPad 300-17ISK': 531, 'Ideapad 700-15ISK': 532, 'GT72VR Dominator': 533, 'V110-15ISK (i5-6200U/4GB/500GB/W10)': 534, 'Yoga 900S-12ISK': 535, 'Chromebook 13': 536, 'Rog GL702VM-GC354T': 537, 'Aspire F5-573G': 538, 'GS70 Stealth': 539, 'G752VY-GC162T (i7-6700HQ/16GB/1TB': 540, 'Latitude E5270': 541, 'Chromebook 15': 542, 'GE72 Apache': 543, '15-bw011nv (A6-9220/4GB/1TB/FHD/W10)': 544, 'Rog GL552VW-CN470T': 545, 'Vostro 3559': 546, 'V110-15ISK (i3-6006U/4GB/128GB/W10)': 547, 'Spectre Pro': 548, 'Portege X30-D-10K': 549, 'Rog GL752VW-T4308T': 550, 'V131 (X5-Z8350/4GB/32GB/FHD/W10)': 551, 'Omen -': 552, '15-bs078cl (i7-7500U/8GB/2TB/W10)': 553, 'ThinkPad P40': 554, 'L403NA-GA013TS (N3350/4GB/32GB/W10)': 555, 'IdeaPad 500-15ISK': 556, 'GP62M 7RDX': 557, 'V110-15ISK (i3-6006U/4GB/1TB/No': 558, '15-BA015wm (E2-7110/4GB/500GB/W10)': 559, 'B51-80 (i5-6200U/8GB/1TB/Radeon': 560, '15-bw002nv (A6-9220/4GB/256GB/Radeon': 561, 'GP72M 7REX': 562, 'ThinkPad T460s': 563, 'B51-80 (i5-6200U/8GB/1008GB/Radeon': 564, 'GS40 Phantom': 565, 'Pavilion 15-cb003nv': 566, 'IdeaPad 310-15ISK': 567, '250 G4': 568, '320-15ISK (i3-6006U/4GB/1TB/GeForce': 569, 'Stream 14-AX000nv': 570, 'PL60 7RD': 571, 'X553SA-XX021T (N3050/4GB/500GB/W10)': 572, 'V110-15ISK (i5-6200U/4GB/500GB/No': 573, 'UX410UA-GV097T (i3-7100U/4GB/256GB/FHD/W10)': 574, 'B51-80 (i7-6500U/4GB/1008GB/FHD/W7)': 575, 'GS60 Ghost': 576, 'Pavilion 15-BC000nv': 577, 'Rog GL552VW-DM201T': 578, 'Chromebook Plus': 579, 'Pavilion Power': 580, 'V110-15ISK (i3-6006U/4GB/1TB/Radeon': 581, 'Rog G752VY-GC229T': 582, 'GS73VR 7RF': 583, 'FX502VM-DM105T (i7-6700HQ/8GB/1TB/GeForce': 584, '15-bs025nv (i5-7200U/8GB/256GB/W10)': 585, 'Aspire E5-774G': 586, 'FX502VM-AS73 (i7-7700HQ/16GB/1TB': 587, 'C740-C9QX (3205U/2GB/32GB/Chrome': 588, 'E5 774G': 589, 'SP714-51 (i7-7Y75/8GB/256GB/FHD/W10)': 590, 'Thinkpad T560': 591, 'GP62MVR 6RF': 592, '15-bw009nv (A12-9720P/6GB/1TB/Radeon': 593, 'Latitude E7270': 594, 'X540SA-RBPDN09 (N3710/4GB/1TB/W10)': 595, 'GL62M 7RDX': 596, 'GE72VR Apache': 597, '15-bs023nv (i3-6006U/4GB/1TB/FHD/W10)': 598, 'GL62 6QF': 599, 'ZenBook UX310UA-WB71': 600, 'Inspiron 7779': 601, 'Rog GL553VE-FY052T': 602, 'Rog GL502VS': 603, 'V510-15IKB (i5-7200U/8GB/256GB/FHD/No': 604, 'ThinkPad L460': 605, 'X541NA-GO020T (N3350/4GB/1TB/W10)': 606, 'Rog G752VT-GC073T': 607, 'B51-80 (i7-6500U/8GB/1008GB/Radeon': 608, 'GE62 Apache': 609, 'Yoga 500-14IBD': 610, 'ZenBook UX305CA-UBM1': 611, 'Aspire ES1-531': 612, 'Pavilion 15-AW003nv': 613, 'Stream 11-Y000na': 614, 'X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce': 615, 'Yoga 500-14ISK': 616, '15-AC110nv (i7-6500U/6GB/1TB/Radeon': 617, 'X553SA-XX031T (N3050/4GB/500GB/W10)': 618}

In [20]:
ScreenResolution_list = df['ScreenResolution'].unique().tolist()
ScreenResolution_dict = {ScreenResolution: i+1 for i, ScreenResolution in enumerate(ScreenResolution_list)}
print(ScreenResolution_dict)
df['ScreenResolution'] = df['ScreenResolution'].map(ScreenResolution_dict)

{'IPS Panel Retina Display 2560x1600': 1, '1440x900': 2, 'Full HD 1920x1080': 3, 'IPS Panel Retina Display 2880x1800': 4, '1366x768': 5, 'IPS Panel Full HD 1920x1080': 6, 'IPS Panel Retina Display 2304x1440': 7, 'IPS Panel Full HD / Touchscreen 1920x1080': 8, 'Full HD / Touchscreen 1920x1080': 9, 'Touchscreen / Quad HD+ 3200x1800': 10, 'IPS Panel Touchscreen 1920x1200': 11, 'Touchscreen 2256x1504': 12, 'Quad HD+ / Touchscreen 3200x1800': 13, 'IPS Panel 1366x768': 14, 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160': 15, 'IPS Panel Full HD 2160x1440': 16, '4K Ultra HD / Touchscreen 3840x2160': 17, 'Touchscreen 2560x1440': 18, '1600x900': 19, 'IPS Panel 4K Ultra HD 3840x2160': 20, '4K Ultra HD 3840x2160': 21, 'Touchscreen 1366x768': 22, 'IPS Panel Full HD 1366x768': 23, 'IPS Panel 2560x1440': 24, 'IPS Panel Full HD 2560x1440': 25, 'IPS Panel Retina Display 2736x1824': 26, 'Touchscreen 2400x1600': 27, '2560x1440': 28, 'IPS Panel Quad HD+ 2560x1440': 29, 'IPS Panel Quad HD+ 3200x1800': 30, 'IPS Panel Quad HD+ / Touchscreen 3200x1800': 31, 'IPS Panel Touchscreen 1366x768': 32, '1920x1080': 33, 'IPS Panel Full HD 1920x1200': 34, 'IPS Panel Touchscreen / 4K Ultra HD 3840x2160': 35, 'IPS Panel Touchscreen 2560x1440': 36, 'Touchscreen / Full HD 1920x1080': 37, 'Quad HD+ 3200x1800': 38, 'Touchscreen / 4K Ultra HD 3840x2160': 39, 'IPS Panel Touchscreen 2400x1600': 40}

In [21]:
TypeName_dict={
    'Ultrabook':1,           'Notebook':2,            'Netbook':3,
             'Gaming':4, '2 in 1 Convertible':5,        'Workstation':6
}
df['TypeName'] = df['TypeName'].map(TypeName_dict)

TypeName_dict

{'Ultrabook': 1,
 'Notebook': 2,
 'Netbook': 3,
 'Gaming': 4,
 '2 in 1 Convertible': 5,
 'Workstation': 6}

In [22]:
df['Ram'] = df['Ram'].str.replace('GB', '').astype(int)

In [23]:
Memory_list = df['Memory'].unique().tolist()
Memory_dict = {Memory: i+1 for i, Memory in enumerate(Memory_list)}
print(Memory_dict)
df['Memory'] = df['Memory'].map(Memory_dict)

{'128GB SSD': 1, '128GB Flash Storage': 2, '256GB SSD': 3, '512GB SSD': 4, '500GB HDD': 5, '256GB Flash Storage': 6, '1TB HDD': 7, '32GB Flash Storage': 8, '128GB SSD +  1TB HDD': 9, '256GB SSD +  256GB SSD': 10, '64GB Flash Storage': 11, '256GB SSD +  1TB HDD': 12, '256GB SSD +  2TB HDD': 13, '32GB SSD': 14, '2TB HDD': 15, '64GB SSD': 16, '1.0TB Hybrid': 17, '512GB SSD +  1TB HDD': 18, '1TB SSD': 19, '256GB SSD +  500GB HDD': 20, '128GB SSD +  2TB HDD': 21, '512GB SSD +  512GB SSD': 22, '16GB SSD': 23, '16GB Flash Storage': 24, '512GB SSD +  256GB SSD': 25, '512GB SSD +  2TB HDD': 26, '64GB Flash Storage +  1TB HDD': 27, '180GB SSD': 28, '1TB HDD +  1TB HDD': 29, '32GB HDD': 30, '1TB SSD +  1TB HDD': 31, '512GB Flash Storage': 32, '128GB HDD': 33, '240GB SSD': 34, '8GB SSD': 35, '508GB Hybrid': 36, '1.0TB HDD': 37, '512GB SSD +  1.0TB Hybrid': 38, '256GB SSD +  1.0TB Hybrid': 39}

In [24]:
Gpu_list = df['Gpu'].unique().tolist()
Gpu_dict = {Gpu: i+1 for i, Gpu in enumerate(Gpu_list)}
print(Gpu_dict)

df['Gpu'] = df['Gpu'].map(Gpu_dict)

{'Intel Iris Plus Graphics 640': 1, 'Intel HD Graphics 6000': 2, 'Intel HD Graphics 620': 3, 'AMD Radeon Pro 455': 4, 'Intel Iris Plus Graphics 650': 5, 'AMD Radeon R5': 6, 'Intel Iris Pro Graphics': 7, 'Nvidia GeForce MX150': 8, 'Intel UHD Graphics 620': 9, 'Intel HD Graphics 520': 10, 'AMD Radeon Pro 555': 11, 'AMD Radeon R5 M430': 12, 'Intel HD Graphics 615': 13, 'AMD Radeon Pro 560': 14, 'Nvidia GeForce 940MX': 15, 'Intel HD Graphics 400': 16, 'Nvidia GeForce GTX 1050': 17, 'AMD Radeon R2': 18, 'AMD Radeon 530': 19, 'Nvidia GeForce 930MX': 20, 'Intel HD Graphics': 21, 'Intel HD Graphics 500': 22, 'Nvidia GeForce 930MX ': 23, 'Nvidia GeForce GTX 1060': 24, 'Nvidia GeForce 150MX': 25, 'Intel Iris Graphics 540': 26, 'AMD Radeon RX 580': 27, 'Nvidia GeForce 920MX': 28, 'AMD Radeon R4 Graphics': 29, 'AMD Radeon 520': 30, 'Nvidia GeForce GTX 1070': 31, 'Nvidia GeForce GTX 1050 Ti': 32, 'Nvidia GeForce MX130': 33, 'AMD R4 Graphics': 34, 'Nvidia GeForce GTX 940MX': 35, 'AMD Radeon RX 560': 36, 'Nvidia GeForce 920M': 37, 'AMD Radeon R7 M445': 38, 'AMD Radeon RX 550': 39, 'Nvidia GeForce GTX 1050M': 40, 'Intel HD Graphics 515': 41, 'AMD Radeon R5 M420': 42, 'Intel HD Graphics 505': 43, 'Nvidia GTX 980 SLI': 44, 'AMD R17M-M1-70': 45, 'Nvidia GeForce GTX 1080': 46, 'Nvidia Quadro M1200': 47, 'Nvidia GeForce 920MX ': 48, 'Nvidia GeForce GTX 950M': 49, 'AMD FirePro W4190M ': 50, 'Nvidia GeForce GTX 980M': 51, 'Intel Iris Graphics 550': 52, 'Nvidia GeForce 930M': 53, 'Intel HD Graphics 630': 54, 'AMD Radeon R5 430': 55, 'Nvidia GeForce GTX 940M': 56, 'Intel HD Graphics 510': 57, 'Intel HD Graphics 405': 58, 'AMD Radeon RX 540': 59, 'Nvidia GeForce GT 940MX': 60, 'AMD FirePro W5130M': 61, 'Nvidia Quadro M2200M': 62, 'AMD Radeon R4': 63, 'Nvidia Quadro M620': 64, 'AMD Radeon R7 M460': 65, 'Intel HD Graphics 530': 66, 'Nvidia GeForce GTX 965M': 67, 'Nvidia GeForce GTX1080': 68, 'Nvidia GeForce GTX1050 Ti': 69, 'Nvidia GeForce GTX 960M': 70, 'AMD Radeon R2 Graphics': 71, 'Nvidia Quadro M620M': 72, 'Nvidia GeForce GTX 970M': 73, 'Nvidia GeForce GTX 960<U+039C>': 74, 'Intel Graphics 620': 75, 'Nvidia GeForce GTX 960': 76, 'AMD Radeon R5 520': 77, 'AMD Radeon R7 M440': 78, 'AMD Radeon R7': 79, 'Nvidia Quadro M520M': 80, 'Nvidia Quadro M2200': 81, 'Nvidia Quadro M2000M': 82, 'Intel HD Graphics 540': 83, 'Nvidia Quadro M1000M': 84, 'AMD Radeon 540': 85, 'Nvidia GeForce GTX 1070M': 86, 'Nvidia GeForce GTX1060': 87, 'Intel HD Graphics 5300': 88, 'AMD Radeon R5 M420X': 89, 'AMD Radeon R7 Graphics': 90, 'Nvidia GeForce 920': 91, 'Nvidia GeForce 940M': 92, 'Nvidia GeForce GTX 930MX': 93, 'AMD Radeon R7 M465': 94, 'AMD Radeon R3': 95, 'Nvidia GeForce GTX 1050Ti': 96, 'AMD Radeon R7 M365X': 97, 'AMD Radeon R9 M385': 98, 'Intel HD Graphics 620 ': 99, 'Nvidia Quadro 3000M': 100, 'Nvidia GeForce GTX 980 ': 101, 'AMD Radeon R5 M330': 102, 'AMD FirePro W4190M': 103, 'AMD FirePro W6150M': 104, 'AMD Radeon R5 M315': 105, 'Nvidia Quadro M500M': 106, 'AMD Radeon R7 M360': 107, 'Nvidia Quadro M3000M': 108, 'Nvidia GeForce 960M': 109, 'ARM Mali T860 MP4': 110}

In [25]:
Cpu_list = df['Cpu'].unique().tolist()
Cpu_dict = {Cpu: i+1 for i, Cpu in enumerate(Cpu_list)}
print(Cpu_dict)

df['Cpu'] = df['Cpu'].map(Cpu_dict)

{'Intel Core i5 2.3GHz': 1, 'Intel Core i5 1.8GHz': 2, 'Intel Core i5 7200U 2.5GHz': 3, 'Intel Core i7 2.7GHz': 4, 'Intel Core i5 3.1GHz': 5, 'AMD A9-Series 9420 3GHz': 6, 'Intel Core i7 2.2GHz': 7, 'Intel Core i7 8550U 1.8GHz': 8, 'Intel Core i5 8250U 1.6GHz': 9, 'Intel Core i3 6006U 2GHz': 10, 'Intel Core i7 2.8GHz': 11, 'Intel Core M m3 1.2GHz': 12, 'Intel Core i7 7500U 2.7GHz': 13, 'Intel Core i7 2.9GHz': 14, 'Intel Core i3 7100U 2.4GHz': 15, 'Intel Atom x5-Z8350 1.44GHz': 16, 'Intel Core i5 7300HQ 2.5GHz': 17, 'AMD E-Series E2-9000e 1.5GHz': 18, 'Intel Core i5 1.6GHz': 19, 'Intel Core i7 8650U 1.9GHz': 20, 'Intel Atom x5-Z8300 1.44GHz': 21, 'AMD E-Series E2-6110 1.5GHz': 22, 'AMD A6-Series 9220 2.5GHz': 23, 'Intel Celeron Dual Core N3350 1.1GHz': 24, 'Intel Core i3 7130U 2.7GHz': 25, 'Intel Core i7 7700HQ 2.8GHz': 26, 'Intel Core i5 2.0GHz': 27, 'AMD Ryzen 1700 3GHz': 28, 'Intel Pentium Quad Core N4200 1.1GHz': 29, 'Intel Atom x5-Z8550 1.44GHz': 30, 'Intel Celeron Dual Core N3060 1.6GHz': 31, 'Intel Core i5 1.3GHz': 32, 'AMD FX 9830P 3GHz': 33, 'Intel Core i7 7560U 2.4GHz': 34, 'AMD E-Series 6110 1.5GHz': 35, 'Intel Core i5 6200U 2.3GHz': 36, 'Intel Core M 6Y75 1.2GHz': 37, 'Intel Core i5 7500U 2.7GHz': 38, 'Intel Core i3 6006U 2.2GHz': 39, 'AMD A6-Series 9220 2.9GHz': 40, 'Intel Core i7 6920HQ 2.9GHz': 41, 'Intel Core i5 7Y54 1.2GHz': 42, 'Intel Core i7 7820HK 2.9GHz': 43, 'Intel Xeon E3-1505M V6 3GHz': 44, 'Intel Core i7 6500U 2.5GHz': 45, 'AMD E-Series 9000e 1.5GHz': 46, 'AMD A10-Series A10-9620P 2.5GHz': 47, 'AMD A6-Series A6-9220 2.5GHz': 48, 'Intel Core i5 2.9GHz': 49, 'Intel Core i7 6600U 2.6GHz': 50, 'Intel Core i3 6006U 2.0GHz': 51, 'Intel Celeron Dual Core 3205U 1.5GHz': 52, 'Intel Core i7 7820HQ 2.9GHz': 53, 'AMD A10-Series 9600P 2.4GHz': 54, 'Intel Core i7 7600U 2.8GHz': 55, 'AMD A8-Series 7410 2.2GHz': 56, 'Intel Celeron Dual Core 3855U 1.6GHz': 57, 'Intel Pentium Quad Core N3710 1.6GHz': 58, 'AMD A12-Series 9720P 2.7GHz': 59, 'Intel Core i5 7300U 2.6GHz': 60, 'AMD A12-Series 9720P 3.6GHz': 61, 'Intel Celeron Quad Core N3450 1.1GHz': 62, 'Intel Celeron Dual Core N3060 1.60GHz': 63, 'Intel Core i5 6440HQ 2.6GHz': 64, 'Intel Core i7 6820HQ 2.7GHz': 65, 'AMD Ryzen 1600 3.2GHz': 66, 'Intel Core i7 7Y75 1.3GHz': 67, 'Intel Core i5 7440HQ 2.8GHz': 68, 'Intel Core i7 7660U 2.5GHz': 69, 'Intel Core i7 7700HQ 2.7GHz': 70, 'Intel Core M m3-7Y30 2.2GHz': 71, 'Intel Core i5 7Y57 1.2GHz': 72, 'Intel Core i7 6700HQ 2.6GHz': 73, 'Intel Core i3 6100U 2.3GHz': 74, 'AMD A10-Series 9620P 2.5GHz': 75, 'AMD E-Series 7110 1.8GHz': 76, 'Intel Celeron Dual Core N3350 2.0GHz': 77, 'AMD A9-Series A9-9420 3GHz': 78, 'Intel Core i7 6820HK 2.7GHz': 79, 'Intel Core M 7Y30 1.0GHz': 80, 'Intel Xeon E3-1535M v6 3.1GHz': 81, 'Intel Celeron Quad Core N3160 1.6GHz': 82, 'Intel Core i5 6300U 2.4GHz': 83, 'Intel Core i3 6100U 2.1GHz': 84, 'AMD E-Series E2-9000 2.2GHz': 85, 'Intel Celeron Dual Core N3050 1.6GHz': 86, 'Intel Core M M3-6Y30 0.9GHz': 87, 'AMD A9-Series 9420 2.9GHz': 88, 'Intel Core i5 6300HQ 2.3GHz': 89, 'AMD A6-Series 7310 2GHz': 90, 'Intel Atom Z8350 1.92GHz': 91, 'Intel Xeon E3-1535M v5 2.9GHz': 92, 'Intel Core i5 6260U 1.8GHz': 93, 'Intel Pentium Dual Core N4200 1.1GHz': 94, 'Intel Celeron Quad Core N3710 1.6GHz': 95, 'Intel Core M 1.2GHz': 96, 'AMD A12-Series 9700P 2.5GHz': 97, 'Intel Core i7 7500U 2.5GHz': 98, 'Intel Pentium Dual Core 4405U 2.1GHz': 99, 'AMD A4-Series 7210 2.2GHz': 100, 'Intel Core i7 6560U 2.2GHz': 101, 'Intel Core M m7-6Y75 1.2GHz': 102, 'AMD FX 8800P 2.1GHz': 103, 'Intel Core M M7-6Y75 1.2GHz': 104, 'Intel Core i5 7200U 2.50GHz': 105, 'Intel Core i5 7200U 2.70GHz': 106, 'Intel Atom X5-Z8350 1.44GHz': 107, 'Intel Core i5 7200U 2.7GHz': 108, 'Intel Core M 1.1GHz': 109, 'Intel Pentium Dual Core 4405Y 1.5GHz': 110, 'Intel Pentium Quad Core N3700 1.6GHz': 111, 'Intel Core M 6Y54 1.1GHz': 112, 'Intel Core i7 6500U 2.50GHz': 113, 'Intel Celeron Dual Core N3350 2GHz': 114, 'Samsung Cortex A72&A53 2.0GHz': 115, 'AMD E-Series 9000 2.2GHz': 116, 'Intel Core M 6Y30 0.9GHz': 117, 'AMD A9-Series 9410 2.9GHz': 118}

In [26]:
OpSys_list = df['OpSys'].unique().tolist()
OpSys_dict = {OpSys: i+1 for i, OpSys in enumerate(OpSys_list)}
print(OpSys_dict)
df['OpSys'] = df['OpSys'].map(OpSys_dict)

{'macOS': 1, 'No OS': 2, 'Windows 10': 3, 'Mac OS X': 4, 'Linux': 5, 'Android': 6, 'Windows 10 S': 7, 'Chrome OS': 8, 'Windows 7': 9}

In [27]:
df['Weight'] = df['Weight'].str.replace('kg', '').astype(float)

In [28]:
df

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,1,1,13.3,1,1,8,1,1,1,1.37,1339.69
1,1,2,1,13.3,2,2,8,2,2,1,1.34,898.94
2,2,3,2,15.6,3,3,8,3,3,2,1.86,575.00
3,1,1,1,15.4,4,4,16,4,4,1,1.83,2537.45
4,1,1,1,13.3,1,5,8,3,5,1,1.37,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...
1270,6,616,5,14.0,8,45,4,1,10,3,1.80,638.00
1271,6,405,5,13.3,31,45,16,4,10,3,1.30,1499.00
1272,6,343,2,14.0,5,86,2,11,21,3,1.50,229.00
1273,2,617,2,15.6,5,45,6,7,102,3,2.19,764.00
1274,4,618,2,15.6,5,86,4,5,21,3,2.20,369.00

In [29]:
df.to_csv('laptopprice_clean.csv')

In [30]:
x = df.drop_duplicates().sum()
x

Company                6275.00
Product              284584.00
TypeName               3256.00
Inches                19154.20
ScreenResolution       8492.00
Cpu                   36210.00
Ram                   10762.00
Memory                 8275.00
Gpu                   27698.00
OpSys                  4300.00
Weight                 2601.67
Price_euros         1447085.55
dtype: float64

In [31]:
df.isnull().sum()

Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
x=df.drop(['Price_euros'],axis=1)
x

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,1,1,1,13.3,1,1,8,1,1,1,1.37
1,1,2,1,13.3,2,2,8,2,2,1,1.34
2,2,3,2,15.6,3,3,8,3,3,2,1.86
3,1,1,1,15.4,4,4,16,4,4,1,1.83
4,1,1,1,13.3,1,5,8,3,5,1,1.37
...,...,...,...,...,...,...,...,...,...,...,...
1270,6,616,5,14.0,8,45,4,1,10,3,1.80
1271,6,405,5,13.3,31,45,16,4,10,3,1.30
1272,6,343,2,14.0,5,86,2,11,21,3,1.50
1273,2,617,2,15.6,5,45,6,7,102,3,2.19
1274,4,618,2,15.6,5,86,4,5,21,3,2.20

In [34]:
y= df[['Price_euros']]
y

      Price_euros
0         1339.69
1          898.94
2          575.00
3         2537.45
4         1803.60
...           ...
1270       638.00
1271      1499.00
1272       229.00
1273       764.00
1274       369.00

[1275 rows x 1 columns]

In [35]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.2, random_state=42)

In [36]:
x_test

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
1179,2,25,2,15.6,5,74,4,5,10,3,2.07
342,2,25,2,15.6,6,15,8,7,23,3,2.10
649,6,265,1,12.5,6,13,8,3,3,3,1.36
772,10,411,2,14.0,14,36,4,1,10,3,1.75
803,5,116,2,15.6,17,17,8,3,17,3,2.06
...,...,...,...,...,...,...,...,...,...,...,...
157,4,104,5,13.3,9,9,8,3,3,3,1.10
1113,2,548,1,13.3,3,45,8,4,10,3,1.16
171,2,111,2,17.3,6,3,6,15,30,3,2.71
16,5,7,2,15.6,3,13,8,3,12,3,2.20
511,3,29,2,15.6,3,13,4,5,15,3,2.20

In [37]:
x_train

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
48,5,7,2,15.6,3,3,4,3,12,3,2.30
191,13,119,2,14.0,6,24,4,8,22,3,1.30
546,6,294,2,14.0,3,3,4,5,3,3,1.87
515,4,281,3,11.6,5,24,2,8,22,3,1.10
658,6,352,4,15.6,6,73,8,9,76,3,3.31
...,...,...,...,...,...,...,...,...,...,...,...
1044,2,101,2,14.0,3,36,4,5,10,3,1.54
1095,3,538,2,15.6,3,3,8,12,49,3,2.40
1130,2,553,2,15.6,5,13,8,15,3,3,2.04
860,6,264,2,15.6,6,3,8,7,3,3,2.30
1126,6,34,5,10.1,11,30,4,11,16,3,0.69

In [38]:
y_test

      Price_euros
1179        650.0
342         716.0
649        1584.0
772        1020.0
803        1749.0
...           ...
157        1315.0
1113       1969.0
171         699.0
16          745.0
511         639.0

[1020 rows x 1 columns]

In [39]:
y_train

      Price_euros
48         639.00
191        260.00
546        785.00
515        245.00
658       1196.00
...           ...
1044      1000.00
1095       799.00
1130       629.00
860        850.66
1126       479.00

[255 rows x 1 columns]

In [40]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((255, 11), (1020, 11), (255, 1), (1020, 1))

# SVM(SVR)

In [47]:
from sklearn.svm import SVR
sv=SVR()
sv.fit(x_train,y_train)

/home/user/Desktop/Training/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [48]:
print('SVR test score:-',sv.score(x_test,y_test))
print('SVR train score:-',sv.score(x_train,y_train))

SVR test score:- -0.029634801778335884
SVR train score:- -0.043709708195906805

# SVM(SVC)

In [ ]:
from sklearn.svm import SVC
sv = SVC()
sv.fit(x_train,y_train)

In [ ]:
print('SVC test score:-',sv.score(x_test,y_test))
print('SVC train score:-',sv.score(x_train,y_train))

# LINEAR REGRESSION

In [41]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [42]:
pred = lr.predict(x_test)
pred

array([[ 806.44419113],
       [1027.233136  ],
       [1036.11655279],
       ...,
       [ 570.22800912],
       [1048.2943224 ],
       [ 602.98601652]], shape=(1020, 1))

In [43]:
y_test

      Price_euros
1179        650.0
342         716.0
649        1584.0
772        1020.0
803        1749.0
...           ...
157        1315.0
1113       1969.0
171         699.0
16          745.0
511         639.0

[1020 rows x 1 columns]

In [44]:
print("tain score:-",lr.score(x_train,y_train))
print("test score:-",lr.score(x_test,y_test))

tain score:- 0.5810833700143032
test score:- 0.5555903876520638

# LOGISTIC REGRESSION

In [49]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(x_train,y_train)

/home/user/Desktop/Training/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

# DecisionTreeClassifier

In [51]:

from sklearn.tree import DecisionTreeClassifier
dt =DecisionTreeClassifier()
dt.fit(x_train, y_train)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [52]:
pred=dt.predict(x_test)
print(pred)
print('DecisionTreeClassifier test score:-',dt.score(x_test,y_test))
print('DecisionTreeClassifier train score:-',dt.score(x_train,y_train))

AttributeError: 'DecisionTreeClassifier' object has no attribute 'tree_'

## with perameter

In [53]:
dt.get_params()


from sklearn.tree import DecisionTreeClassifier
dt =DecisionTreeClassifier(criterion='entropy', min_samples_split=3, min_samples_leaf=2, random_state=42)
dt.fit(x_train, y_train)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [54]:
pred=dt.predict(x_test)
print(pred)
print('DecisionTreeClassifier test score:-',dt.score(x_test,y_test))
print('DecisionTreeClassifier train score:-',dt.score(x_train,y_train))

AttributeError: 'DecisionTreeClassifier' object has no attribute 'tree_'

# DecisionTreeRegressor

In [55]:
from sklearn.tree import DecisionTreeRegressor
dt =DecisionTreeRegressor()
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [57]:

print('DecisionTreeRegressor test score:-',dt.score(x_test,y_test))
print('DecisionTreeRegressor train score:-',dt.score(x_train,y_train))

DecisionTreeRegressor test score:- 0.4682749200193155
DecisionTreeRegressor train score:- 0.9998761749850807

## with perameter

In [58]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(criterion='squared_error',min_samples_split=3,min_samples_leaf=2,random_state=42)
dt.fit(x_train, y_train)

DecisionTreeRegressor(min_samples_leaf=2, min_samples_split=3, random_state=42)

In [59]:

print("DecisionTreeRegressor Test Score:", dt.score(x_test, y_test))
print("DecisionTreeRegressor Train Score:", dt.score(x_train, y_train))

DecisionTreeRegressor Test Score: 0.5647498288254689
DecisionTreeRegressor Train Score: 0.9560936397332984

In [60]:
import joblib

In [63]:
joblib.dump(dt, 'DecisionTreeRegressor_model.lb')
print("Model saved successfully!")

model=joblib.load('DecisionTreeRegressor_model.lb')
# print(model.predict(x_test))

Model saved successfully!