In [377]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [378]:
df = pd.read_csv("/home/user/Desktop/Training/Project/Medical/Data/medical_disease_prediction_10000.csv")
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,Male,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,69,Male,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,47,Female,23.9,105,162,253,68,No,No,Low,No,Healthy
4,47,Male,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [379]:
print(df.head())

   Age  Gender   BMI  BloodPressure  GlucoseLevel  Cholesterol  HeartRate  \
0   23    Male  17.5            102           177          161         88
1   69    Male  31.1            118           256          147         92
2   61  Female  31.3            114           206          193         74
3   47  Female  23.9            105           162          253         68
4   47    Male  28.3            148           121          280         84

  Smoking Alcohol PhysicalActivity FamilyHistory       Disease
0      No      No           Medium            No       Healthy
1      No      No             High           Yes  Pre-Diabetes
2     Yes      No           Medium            No       Healthy
3      No      No              Low            No       Healthy
4      No     Yes             High            No       Healthy

In [380]:
print("Shape of Dataset:", df.shape)

Shape of Dataset: (10000, 12)

In [381]:
print(df.columns)

Index(['Age', 'Gender', 'BMI', 'BloodPressure', 'GlucoseLevel', 'Cholesterol',
       'HeartRate', 'Smoking', 'Alcohol', 'PhysicalActivity', 'FamilyHistory',
       'Disease'],
      dtype='str')

In [382]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               10000 non-null  int64
 1   Gender            10000 non-null  str
 2   BMI               10000 non-null  float64
 3   BloodPressure     10000 non-null  int64
 4   GlucoseLevel      10000 non-null  int64
 5   Cholesterol       10000 non-null  int64
 6   HeartRate         10000 non-null  int64
 7   Smoking           10000 non-null  str
 8   Alcohol           10000 non-null  str
 9   PhysicalActivity  10000 non-null  str
 10  FamilyHistory     10000 non-null  str
 11  Disease           10000 non-null  str
dtypes: float64(1), int64(5), str(6)
memory usage: 937.6 KB
None

In [383]:
print(df.isnull().sum())

Age                 0
Gender              0
BMI                 0
BloodPressure       0
GlucoseLevel        0
Cholesterol         0
HeartRate           0
Smoking             0
Alcohol             0
PhysicalActivity    0
FamilyHistory       0
Disease             0
dtype: int64

In [384]:
print( df.duplicated().sum())

0

In [385]:
df = df.drop_duplicates()

In [386]:
print( df.duplicated().sum())

0

In [387]:
print(df.describe())

                Age           BMI  BloodPressure  GlucoseLevel   Cholesterol  \
count  10000.000000  10000.000000   10000.000000  10000.000000  10000.000000
mean      50.755300     26.082000     135.023800    175.252000    219.313500
std       19.242137      4.461098      26.249406     60.536159     57.940956
min       18.000000     16.000000      90.000000     70.000000    120.000000
25%       34.000000     23.000000     112.000000    123.000000    169.000000
50%       51.000000     26.000000     135.000000    174.000000    219.000000
75%       67.000000     29.100000     158.000000    227.000000    269.250000
max       84.000000     44.700000     180.000000    280.000000    320.000000

          HeartRate
count  10000.000000
mean      82.690100
std       16.167628
min       55.000000
25%       69.000000
50%       83.000000
75%       97.000000
max      110.000000

In [388]:
for col in df.columns:
    print("\nColumn:", col)
    print(df[col].unique())

Column: Age
[23 69 61 47 75 64 31 24 53 83 67 68 66 70 52 26 74 48 51 42 30 80 44 73
 54 33 55 77 22 36 60 29 41 63 49 20 28 79 82 45 39 78 71 40 62 81 38 43
 37 34 27 18 65 56 25 58 32 84 21 46 72 19 35 57 59 50 76]

Column: Gender
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

Column: BMI
[17.5 31.1 31.3 23.9 28.3 25.  27.1 20.8 28.8 18.6 17.8 25.5 27.2 23.1
 34.5 26.7 27.  26.9 30.5 28.6 28.  29.3 18.  25.7 25.1 26.1 20.4 26.
 20.  27.7 27.6 19.4 24.3 30.  23.  19.2 18.4 26.5 28.5 28.7 25.9 24.8
 21.2 24.  20.1 22.2 26.4 39.8 19.9 25.4 19.6 24.4 29.8 24.1 19.7 26.3
 24.9 18.3 28.4 22.9 29.4 31.9 25.2 21.4 24.6 23.5 28.2 28.1 22.5 28.9
 17.1 31.7 27.8 20.6 29.1 23.8 29.7 17.9 21.3 16.7 22.  32.8 35.3 19.
 23.4 32.5 22.6 27.3 23.2 34.8 25.8 32.9 30.8 25.6 19.5 31.5 27.9 21.6
 23.7 34.3 35.  21.8 29.9 31.8 26.6 19.1 26.8 29.5 22.4 16.4 25.3 30.7
 29.6 30.6 16.  33.8 37.1 18.1 24.5 30.9 20.2 30.3 30.1 27.4 32.2 17.7
 23.6 33.3 24.7 32.6 18.9 22.3 22.8 31.6 18.8 35.4 18.7 35.6 20.7 27.5
 16.1 36.6 20.9 34.1 20.3 39.7 21.9 17.4 36.4 21.1 22.7 22.1 36.1 21.5
 23.3 30.2 37.8 18.2 21.7 26.2 16.5 38.1 33.9 33.4 20.5 34.9 31.4 19.8
 29.  34.  24.2 31.2 33.2 33.6 35.8 21.  33.7 29.2 32.  37.7 33.5 30.4
 35.5 16.9 32.1 31.  32.4 19.3 32.3 33.  40.1 18.5 34.7 17.2 16.6 17.6
 32.7 34.4 35.7 36.8 35.2 33.1 36.  17.  36.2 17.3 39.6 36.9 40.4 16.3
 34.6 36.7 16.8 38.4 34.2 37.5 44.7 36.5 38.7 35.1 38.9 35.9 39.2 37.2
 36.3 37.4 39.3 16.2 40.  37.  37.9 38.8 38.  38.6 39.  37.3 40.2 39.5]

Column: BloodPressure
[102 118 114 105 148  90 125 101 145 158 132 130 108 124 174  93 161 104
 100 115 167 172 153 103 176  96 160  98 120 139 154 112 119 107 106 142
 166  91  95 138 152 121 147 165 159 162 178 143 126 122 164 116 135 131
  97 117 170 180 175 149 146 144  99 109 168  92 155 133 141 128 137 173
 163 110 127 136 157 171 179 134 156 140  94 123 177 151 129 111 169 113
 150]

Column: GlucoseLevel
[177 256 206 162 121 136  85 102  76 169  78 104 215 141 110  81 113  93
  86 210  96 268 172 156 254 234 158 275 181 219 274 222 194 199 208 276
 217 133  74 235 157 267  77 226 264 245 253 252 214 142 227  89 131 114
 190 161 203 192 213  82 242  75 179 239 231 196 107 271 143 229 200 236
 178 243 106  80 174 163 204 145  70 220  98 198 230 191 218 129 108 273
 269 167 205 103 137 251  72  88 101 257 115 149  83 241 207 260 233 140
 223 248 216 221 128  94 202 159 180 270 139 250 237  92 262 201 144 105
 211 117 280 232 119 164 224 197 279 123 165 160 166 263 150 100 116  87
 148 184 212 189 249 183 171  99 152 244  73 187 153  95 132 151 240 265
 193 118 246 186 138 176 228 147 130  91 272 135  90 112 247  84 154  71
 188 277 126 266 259 124  97  79 134 278 238 209 225 185 111 109 125 173
 120 155 122 255 195 258 175 168 127 182 146 170 261]

Column: Cholesterol
[161 147 193 253 280 126 212 308 285 312 138 256 230 215 307 213 250 216
 247 315 283 166 294 225 237 143 209 180 137 291 145 264 269 243 288 142
 123 290 156 179 258 227 160 224 305 232 188 221 266 201 292 260 229 165
 296 131 129 277 125 222 157 173 195 132 158 176 144 298 263 181 208 274
 313 223 170 282 265 279 231 241 192 276 124 204 303 168 220 141 299 273
 148 251 121 130 153 184 310 267 122 246 293 203 135 151 268 262 316 205
 278 183 199 162 152 206 140 257 275 207 236 301 238 194 159 317 178 200
 154 318 240 182 217 175 163 271 281 120 309 210 169 196 234 289 248 311
 139 244 259 164 197 306 255 127 167 189 172 198 155 186 304 235 218 252
 214 134 171 239 245 174 233 286 149 261 202 219 254 272 190 297 319 133
 300 191 228 249 284 150 270 287 314 295 211 146 226 177 185 320 302 136
 242 187 128]

Column: HeartRate
[ 88  92  74  68  84  59  71 107  97  72  58  76  93  57 103 104  89  64
  69  81 109  99  62  87  90  63  66 105  56  86 102  94  79  61 106  73
  77  95  60  83  55  65 100 110  98 101  70  75  67  80  91  85 108  82
  96  78]

Column: Smoking
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Column: Alcohol
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Column: PhysicalActivity
<StringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: str

Column: FamilyHistory
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Column: Disease
<StringArray>
['Healthy', 'Pre-Diabetes', 'Hypertension', 'Heart Disease', 'Diabetes']
Length: 5, dtype: str

In [389]:
int_df = df.copy()

In [390]:
int_df['Gender'] = int_df['Gender'].map({
    'Male':0,
    'Female':1
})

int_df['Smoking'] = int_df['Smoking'].map({
    'No':0,
    'Yes':1
})

int_df['Alcohol'] = int_df['Alcohol'].map({
    'No':0,
    'Yes':1
})

int_df['FamilyHistory'] = int_df['FamilyHistory'].map({
    'No':0,
    'Yes':1
})

In [391]:
corr_matrix = int_df.corr(numeric_only=True)

print(corr_matrix)

                    Age    Gender       BMI  BloodPressure  GlucoseLevel  \
Age            1.000000  0.008355  0.001692       0.004120     -0.017341
Gender         0.008355  1.000000 -0.002708       0.013336     -0.010412
BMI            0.001692 -0.002708  1.000000       0.013818      0.003975
BloodPressure  0.004120  0.013336  0.013818       1.000000     -0.008727
GlucoseLevel  -0.017341 -0.010412  0.003975      -0.008727      1.000000
Cholesterol   -0.016758 -0.016176  0.011252       0.007915      0.011214
HeartRate      0.005707  0.009218  0.001657       0.005419      0.006456
Smoking       -0.001711  0.001650  0.031973       0.005612     -0.002740
Alcohol        0.020003  0.008664  0.003481      -0.004256      0.030173
FamilyHistory -0.009349 -0.002337  0.015278       0.005473      0.001456

               Cholesterol  HeartRate   Smoking   Alcohol  FamilyHistory
Age              -0.016758   0.005707 -0.001711  0.020003      -0.009349
Gender           -0.016176   0.009218  0.001650  0.008664      -0.002337
BMI               0.011252   0.001657  0.031973  0.003481       0.015278
BloodPressure     0.007915   0.005419  0.005612 -0.004256       0.005473
GlucoseLevel      0.011214   0.006456 -0.002740  0.030173       0.001456
Cholesterol       1.000000   0.010750 -0.010691  0.010113       0.005772
HeartRate         0.010750   1.000000  0.009586 -0.017800      -0.011915
Smoking          -0.010691   0.009586  1.000000  0.007855      -0.017419
Alcohol           0.010113  -0.017800  0.007855  1.000000       0.024795
FamilyHistory     0.005772  -0.011915 -0.017419  0.024795       1.000000

In [392]:
int_df.to_csv("medical_disease_cleaned.csv",index=False)

In [393]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,Male,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,69,Male,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,47,Female,23.9,105,162,253,68,No,No,Low,No,Healthy
4,47,Male,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [394]:
df['Disease'].unique()

<StringArray>
['Healthy', 'Pre-Diabetes', 'Hypertension', 'Heart Disease', 'Diabetes']
Length: 5, dtype: str

In [395]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [396]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,Male,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,69,Male,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,47,Female,23.9,105,162,253,68,No,No,Low,No,Healthy
4,47,Male,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [397]:
Disease_dict = {
    'Healthy':1, 'Pre-Diabetes':2, 'Hypertension':3, 'Heart Disease':4, 'Diabetes':5
}

df['Disease']=df['Disease'].map(Disease_dict)

In [398]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,Male,17.5,102,177,161,88,No,No,Medium,No,1
1,69,Male,31.1,118,256,147,92,No,No,High,Yes,2
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,1
3,47,Female,23.9,105,162,253,68,No,No,Low,No,1
4,47,Male,28.3,148,121,280,84,No,Yes,High,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No,3
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,3
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,3
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,2
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes,2

In [399]:
x = df.drop("Disease",axis =1)
y = df["Disease"]

In [400]:
y

0       1
1       2
2       1
3       1
4       1
       ..
9995    3
9996    3
9997    3
9998    2
9999    2
Name: Disease, Length: 10000, dtype: int64

In [401]:
x

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
0,23,Male,17.5,102,177,161,88,No,No,Medium,No
1,69,Male,31.1,118,256,147,92,No,No,High,Yes
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No
3,47,Female,23.9,105,162,253,68,No,No,Low,No
4,47,Male,28.3,148,121,280,84,No,Yes,High,No
...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes

In [402]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [403]:
x_test

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
6252,36,Male,23.5,122,156,146,99,No,Yes,Medium,Yes
4684,52,Female,23.0,147,137,273,107,No,No,High,No
1731,78,Male,26.3,118,128,125,55,No,No,Medium,Yes
4742,46,Male,22.6,161,211,147,59,No,No,Low,No
4521,64,Female,27.2,126,261,162,108,Yes,Yes,Medium,No
...,...,...,...,...,...,...,...,...,...,...,...
6412,23,Female,25.5,114,204,220,99,No,No,Low,No
8285,20,Male,32.3,131,257,287,77,No,No,Low,No
7853,53,Female,26.8,180,240,306,94,No,No,High,No
1095,23,Female,35.2,118,148,292,100,No,No,Low,No
6929,68,Female,16.5,105,117,307,62,No,No,Medium,No

In [404]:
x_train

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
9254,76,Male,29.6,134,266,318,101,Yes,No,Medium,Yes
1561,35,Female,29.3,96,220,300,58,No,No,Low,No
1670,69,Male,29.6,164,149,229,98,No,No,Low,No
6087,47,Male,29.0,159,250,258,109,No,Yes,Medium,No
6669,42,Male,23.4,107,224,300,82,Yes,No,Medium,No
...,...,...,...,...,...,...,...,...,...,...,...
5734,61,Female,30.2,175,147,167,102,No,Yes,Low,No
5191,79,Female,20.5,150,225,142,84,No,No,Medium,Yes
5390,30,Male,27.6,119,101,129,110,No,No,Medium,No
860,82,Male,30.7,108,143,231,102,Yes,No,Low,Yes
7270,38,Male,17.3,176,89,284,66,No,Yes,High,Yes

In [405]:
y_train

9254    3
1561    1
1670    1
6087    1
6669    1
       ..
5734    2
5191    1
5390    1
860     3
7270    3
Name: Disease, Length: 8000, dtype: int64

In [406]:
y_test

6252    1
4684    1
1731    1
4742    1
4521    3
       ..
6412    1
8285    1
7853    3
1095    1
6929    1
Name: Disease, Length: 2000, dtype: int64

In [407]:
df["Gender"] = df["Gender"].replace({
    "Male": 1,
    "Female": 0
})

In [408]:
print(df["Gender"].head())
print(df["Gender"].dtype)

0    1
1    1
2    0
3    0
4    1
Name: Gender, dtype: object
object

In [409]:
df["Gender"] = df["Gender"].map({
    "Male": 1,
    "Female": 0
})

In [ ]:
from sklearn.svm import SVC,SVR
sv=SVR()
sv.fit(x_train,y_train)
pred = sv.predict(x_train)
pred

ValueError: could not convert string to float: 'Male'